# Copyright (C) 2026 Linuxfabrik <info@linuxfabrik.ch>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# On Debian systems, the complete text of the GNU General Public License
# version 2 can be found in /usr/share/common-licenses/GPL-2.
#
# SPDX-License-Identifier: GPL-2.0-or-later

"""Import of a running ruleset: iptables-save and ``nft -j list ruleset``.

The parsers are asked what they read, the builder what it made of it, and
the result is compiled with both compilers - an import that produces a
firewall the compilers refuse has imported nothing.  The nftables listing
is the one nft 1.1.6 printed for ``fixtures/import/sample.nft``; the
iptables-save files are a hand-written sample and the test input of
Firewall Builder's importer (``src/unit_tests/ImporterTest/test_data``).
"""

import importlib.resources
import json
import re
import subprocess  # nosec B404
import uuid
from pathlib import Path

import pytest
import sqlalchemy

pytest.importorskip('PySide6')

from firewallfabrik.core._database import DatabaseManager
from firewallfabrik.core.objects import (
    CustomService,
    Firewall,
    FWObjectDatabase,
    Library,
    PolicyRule,
    rule_elements,
)
from firewallfabrik.gui.object_tree_data import (
    SYSTEM_GROUP_PATHS,
    create_library_folder_structure,
)
from firewallfabrik.importer import (
    apply_plan,
    parse_ip_addr_json,
    parse_ip_route_json,
    parse_iptables_save,
    parse_nft_json,
    plan_import,
)
from tests.tool_probe import CAN_ASK_NFT, SKIP_REASON

IMPORT_DIR = Path(__file__).parent / 'fixtures' / 'import'


def _text(name):
    return (IMPORT_DIR / name).read_text()


def _new_database():
    """A data file the way File > New makes one: Standard plus User."""
    db_manager = DatabaseManager()
    std = (
        Path(str(importlib.resources.files('firewallfabrik') / 'resources'))
        / 'libraries'
        / 'standard.fwf'
    )
    db_manager._load_yaml(std)
    with db_manager.session() as session:
        db = session.scalars(sqlalchemy.select(FWObjectDatabase)).first()
        library = Library(id=uuid.uuid4(), name='User', database=db)
        session.add(library)
        session.flush()
        create_library_folder_structure(session, library.id)
        library_id = library.id
    return db_manager, library_id


def _import(rulesets, platform, name='imported', **kwargs):
    db_manager, library_id = _new_database()
    plan = plan_import(
        db_manager,
        library_id,
        rulesets,
        name,
        platform,
        group_paths=SYSTEM_GROUP_PATHS,
        **kwargs,
    )
    fw_id, unresolved = apply_plan(
        db_manager, library_id, plan, group_paths=SYSTEM_GROUP_PATHS
    )
    assert unresolved == []
    return db_manager, fw_id, plan


def _compile(db_manager, fw_name, tmp_path, platform):
    data_file = tmp_path / 'imported.fwf'
    db_manager.save(data_file)
    db = DatabaseManager()
    db.load(data_file)
    with db.session() as session:
        fw_id = session.scalars(
            sqlalchemy.select(Firewall.id).where(Firewall.name == fw_name)
        ).one()
    if platform == 'ipt':
        from firewallfabrik.platforms.iptables._compiler_driver import (
            CompilerDriver_ipt as Driver,
        )
    else:
        from firewallfabrik.platforms.nftables._compiler_driver import (
            CompilerDriver_nft as Driver,
        )
    driver = Driver(db)
    driver.wdir = str(tmp_path)
    driver.file_name_setting = f'{fw_name}-{platform}.fw'
    driver.run(cluster_id='', fw_id=str(fw_id), single_rule_id='')
    return driver, tmp_path / f'{fw_name}-{platform}.fw'


def _rules(db_manager, fw_id, rule_set_name):
    with db_manager.session() as session:
        fw = session.get(Firewall, fw_id)
        rule_set = next(rs for rs in fw.rule_sets if rs.name == rule_set_name)
        rules = sorted(rule_set.rules, key=lambda r: r.position)
        result = []
        for rule in rules:
            rows = session.execute(
                sqlalchemy.select(
                    rule_elements.c.slot, rule_elements.c.target_id
                ).where(rule_elements.c.rule_id == rule.id)
            ).all()
            result.append((dict(rule.options or {}), rule.comment, rows))
        return result


# -- iptables-save --


def test_iptables_save_header_names_the_family_and_release():
    ruleset = parse_iptables_save(
        '# Generated by ip6tables-save v1.8.11 on Wed Oct  1 10:00:00 2026\n'
        '*filter\n:INPUT DROP [0:0]\n-A INPUT -s 2001:db8::/32 -j ACCEPT\nCOMMIT\n'
    )
    table = ruleset.tables[0]
    assert ruleset.version == '1.8.11'
    assert table.family == 6
    assert table.chains['INPUT'].policy == 'drop'
    assert table.chains['INPUT'].rules[0].src[0].text == '2001:db8::/32'


def test_iptables_save_reads_matches_and_targets():
    ruleset = parse_iptables_save(_text('sample-iptables-save.txt'))
    chains = {t.name: t.chains for t in ruleset.tables}
    ssh = chains['filter']['INPUT'].rules[2]
    assert [a.text for a in ssh.src] == ['192.0.2.0/24']
    assert ssh.services[0].dst_ports[0].low == 22
    assert ssh.comment == 'ssh "admin"'
    ping = chains['filter']['INPUT'].rules[3]
    assert (ping.services[0].protocol, ping.services[0].icmp_type) == ('icmp', 8)
    assert (ping.limit_rate, ping.limit_unit) == (5, 'second')
    multiport = chains['filter']['INPUT'].rules[4]
    assert [(p.low, p.high) for p in multiport.services[0].dst_ports] == [
        (80, 80),
        (443, 443),
        (8000, 8080),
    ]
    assert (multiport.action, multiport.jump_target) == ('jump', 'svc')
    dnat = chains['nat']['PREROUTING'].rules[0]
    assert dnat.action == 'dnat'
    assert dnat.nat_addresses[0].text == '192.168.1.10'
    assert dnat.nat_ports.low == 8080


def test_iptables_save_keeps_a_rule_it_cannot_read_and_says_why():
    ruleset = parse_iptables_save(_text('sample-iptables-save.txt'))
    forward = next(t for t in ruleset.tables if t.name == 'filter').chains['FORWARD']
    assert forward.rules[1].unsupported == ['-m recent --set']


def test_iptables_save_reads_the_old_negation_and_names():
    ruleset = parse_iptables_save(
        '*filter\n:INPUT DROP [0:0]\n'
        '-A INPUT -s ! 192.0.2.0/24 -p tcp --dport smtp -j ACCEPT\n'
        '-A INPUT -p icmp --icmp-type network-unknown -j ACCEPT\n'
        '[3:180] -A INPUT -p tcp -m multiport --ports 22,80 -j ACCEPT\n'
        'COMMIT\n'
    )
    smtp, icmp, ports = ruleset.tables[0].chains['INPUT'].rules
    assert smtp.src_negated is True
    assert smtp.services[0].dst_ports[0].low == 25
    assert (icmp.services[0].icmp_type, icmp.services[0].icmp_code) == (3, 6)
    # --ports: the source port or the destination port, two services.
    assert [(bool(s.src_ports), bool(s.dst_ports)) for s in ports.services] == [
        (False, True),
        (True, False),
    ]


def test_iptables_save_reports_the_tables_it_leaves_out():
    ruleset = parse_iptables_save(
        '*mangle\n:PREROUTING ACCEPT [0:0]\n-A PREROUTING -j MARK --set-mark 1\n'
        'COMMIT\n*raw\n:PREROUTING ACCEPT [0:0]\nCOMMIT\n'
    )
    assert ruleset.tables == []
    # The empty raw table every iptables-save lists is not worth a word.
    assert [m[1] for m in ruleset.messages] == [
        'The mangle table is not imported (1 rules): FirewallFabrik builds it '
        'from the marking and classification options of policy rules.'
    ]


def test_a_rate_limit_written_as_hashlimit_is_the_rule_limit():
    ruleset = parse_iptables_save(
        '*filter\n:INPUT DROP [0:0]\n-A INPUT -p tcp --dport 22 -m hashlimit '
        '--hashlimit-above 3/min --hashlimit-burst 5 --hashlimit-name limit_rule_0 '
        '-j DROP\nCOMMIT\n'
    )
    rule = ruleset.tables[0].chains['INPUT'].rules[0]
    assert rule.unsupported == []
    assert (rule.limit_rate, rule.limit_unit, rule.limit_burst, rule.limit_over) == (
        3,
        'minute',
        5,
        True,
    )


# -- nft -j list ruleset --


def test_nft_json_reads_tables_chains_sets_and_rules():
    ruleset = parse_nft_json(_text('sample-nft.json'))
    assert ruleset.version == '1.1.6'
    tables = {t.name: t for t in ruleset.tables}
    assert (tables['t'].kind, tables['t'].family) == ('filter', None)
    assert (tables['n'].kind, tables['n'].family) == ('nat', 4)
    assert [a.text for a in ruleset.sets['admins'].addresses] == [
        '192.0.2.0/24',
        '198.51.100.7',
    ]
    rules = tables['t'].chains['input'].rules
    admins = rules[3]
    assert (admins.src_set, admins.comment) == ('admins', 'ssh admins')
    negated = rules[4]
    assert negated.src_negated is True
    assert [a.text for a in negated.src] == ['10.0.0.0/8', '172.16.0.1-172.16.0.9']
    assert negated.states == {'new'}
    either = rules[8]
    assert sorted(s.protocol for s in either.services) == ['tcp', 'udp']
    reset = rules[12]
    assert (reset.action, reset.reject_with) == ('reject', 'tcp-reset')


def test_nft_json_flags_an_iptables_nft_statement():
    ruleset = parse_nft_json(
        '{"nftables": [{"table": {"family": "ip", "name": "filter"}},'
        '{"chain": {"family": "ip", "table": "filter", "name": "INPUT",'
        ' "type": "filter", "hook": "input", "prio": 0, "policy": "accept"}},'
        '{"rule": {"family": "ip", "table": "filter", "chain": "INPUT",'
        ' "expr": [{"xt": {"type": "match", "name": "conntrack"}}, {"accept": null}]}}]}'
    )
    rule = ruleset.tables[0].chains['INPUT'].rules[0]
    assert 'iptables-save' in rule.unsupported[0]


def test_nft_json_that_is_none_says_so():
    assert parse_nft_json('not json').messages[0][0] == 'error'


# -- the firewall the builder makes --


def test_import_reuses_existing_objects_and_builds_rule_sets():
    db_manager, fw_id, plan = _import(
        [parse_iptables_save(_text('sample-iptables-save.txt'))], 'iptables', 'fw'
    )
    names = {obj['name'] for obj in plan.objects}
    # ssh, http and https come from the Standard library.
    assert 'tcp dport 22' not in names
    assert 'tcp dport 8000-8080' in names
    with db_manager.session() as session:
        fw = session.get(Firewall, fw_id)
        rule_sets = {(rs.type, rs.name, rs.top) for rs in fw.rule_sets}
        interfaces = {i.name: (i.data or {}).get('dyn') for i in fw.interfaces}
    assert ('Policy', 'Policy', True) in rule_sets
    assert ('Policy', 'svc', False) in rule_sets
    assert ('NAT', 'NAT', True) in rule_sets
    # Addresses the ruleset does not name are found at run time.
    assert interfaces == {'lo': False, 'eth0': True, 'eth1': True}


def test_import_disables_and_marks_a_rule_it_cannot_carry_over():
    db_manager, fw_id, _plan = _import(
        [parse_iptables_save(_text('sample-iptables-save.txt'))], 'iptables', 'fw'
    )
    disabled = [
        (options, comment)
        for options, comment, _rows in _rules(db_manager, fw_id, 'Policy')
        if options.get('disabled')
    ]
    assert len(disabled) == 1
    options, comment = disabled[0]
    assert 'Not imported: -m recent --set.' in comment
    assert options.get('color') == '#C86E6E'


def test_a_log_rule_and_the_rule_it_logs_for_become_one_logged_rule():
    db_manager, fw_id, _plan = _import(
        [parse_iptables_save(_text('sample-iptables-save.txt'))], 'iptables', 'fw'
    )
    logged = [
        options
        for options, _comment, _rows in _rules(db_manager, fw_id, 'Policy')
        if options.get('log')
    ]
    assert len(logged) == 1
    assert logged[0]['log_prefix'] == 'smtp '
    assert logged[0]['log_level'] == 'info'


def test_both_interfaces_become_a_branch_into_a_rule_set_of_their_own():
    db_manager, fw_id, _plan = _import(
        [parse_iptables_save(_text('sample-iptables-save.txt'))], 'iptables', 'fw'
    )
    with db_manager.session() as session:
        fw = session.get(Firewall, fw_id)
        nested = [rs for rs in fw.rule_sets if rs.name.startswith('FORWARD_')]
        assert len(nested) == 1
        (inner,) = nested[0].rules
        assert inner.policy_direction is not None


def test_the_leading_state_rules_of_every_chain_become_the_options():
    _db, _fw, plan = _import([parse_nft_json(_text('sample-nft.json'))], 'nftables')
    options = plan.firewall['options']
    assert options['accept_established'] is True
    assert options['drop_invalid'] is True
    assert options['log_invalid'] is False


def test_a_state_next_to_a_service_branches(tmp_path):
    db_manager, fw_id, _plan = _import(
        [
            parse_iptables_save(
                '*filter\n:INPUT DROP [0:0]\n'
                '-A INPUT -p tcp --dport 22 -m state --state NEW,ESTABLISHED -j ACCEPT\n'
                'COMMIT\n'
            )
        ],
        'iptables',
        'fw',
    )
    with db_manager.session() as session:
        fw = session.get(Firewall, fw_id)
        nested = next(rs for rs in fw.rule_sets if rs.name.startswith('INPUT_'))
        (inner,) = nested.rules
        target = session.execute(
            sqlalchemy.select(rule_elements.c.target_id).where(
                rule_elements.c.rule_id == inner.id, rule_elements.c.slot == 'srv'
            )
        ).scalar_one()
        service = session.get(CustomService, target)
        assert service.codes['nftables'] == 'ct state established,new'
        outer = next(rs for rs in fw.rule_sets if rs.name == 'Policy').rules[0]
        assert isinstance(outer, PolicyRule)
        assert (outer.options or {}).get('branch_id')


@pytest.mark.parametrize('platform', ['ipt', 'nft'])
@pytest.mark.parametrize(
    ('source', 'fixture'),
    [
        ('iptables', 'sample-iptables-save.txt'),
        ('iptables', 'fwbuilder-ipt.test'),
        ('nftables', 'sample-nft.json'),
    ],
)
def test_an_imported_firewall_compiles(tmp_path, platform, source, fixture):
    parse = parse_iptables_save if source == 'iptables' else parse_nft_json
    db_manager, _fw_id, _plan = _import([parse(_text(fixture))], source, 'fw')
    driver, script = _compile(db_manager, 'fw', tmp_path, platform)
    assert driver.all_errors == [], driver.all_errors
    assert script.exists()


@pytest.mark.skipif(not CAN_ASK_NFT, reason=SKIP_REASON)
@pytest.mark.parametrize(
    ('source', 'fixture'),
    [
        ('iptables', 'sample-iptables-save.txt'),
        ('iptables', 'fwbuilder-ipt.test'),
        ('nftables', 'sample-nft.json'),
    ],
)
def test_an_imported_firewall_loads(tmp_path, source, fixture):
    """nft accepts what the compiler made of the import."""
    parse = parse_iptables_save if source == 'iptables' else parse_nft_json
    db_manager, _fw_id, _plan = _import([parse(_text(fixture))], source, 'fw')
    _driver, script = _compile(db_manager, 'fw', tmp_path, 'nft')
    match = re.search(
        r"<<\s*'?NFT_RULES'?\n(.*?)^NFT_RULES$", script.read_text(), re.M | re.S
    )
    rules = tmp_path / 'rules.nft'
    rules.write_text(match.group(1))
    result = subprocess.run(  # nosec B603 B607
        ['unshare', '-rn', 'nft', '--check', '-f', str(rules)],
        capture_output=True,
        text=True,
        check=False,
        timeout=60,
    )
    assert result.returncode == 0, result.stderr


def test_the_addresses_input_rules_are_for_belong_to_the_firewall():
    """A destination in the input chain is an address of this machine."""
    db_manager, fw_id, plan = _import(
        [
            parse_iptables_save(
                '*filter\n:INPUT DROP [0:0]\n'
                '-A INPUT -d 192.0.2.1/32 -p tcp --dport 22 -j ACCEPT\n'
                '-A INPUT -d 198.51.100.0/24 -p tcp --dport 80 -j ACCEPT\n'
                'COMMIT\n'
            )
        ],
        'iptables',
        'fw',
    )
    imported = plan.firewall['interfaces'][-1]
    assert imported['name'] == 'imported'
    assert imported['data'] == {'unprotected': True}
    assert [a['inet_addr_mask']['address'] for a in imported['addresses']] == [
        '192.0.2.1'
    ]
    # A network on the local side goes behind the firewall.
    with db_manager.session() as session:
        fw = session.get(Firewall, fw_id)
        assert any(rs.name.startswith('INPUT_') for rs in fw.rule_sets)


def test_known_interface_addresses_are_the_interfaces():
    db_manager, library_id = _new_database()
    plan = plan_import(
        db_manager,
        library_id,
        [parse_iptables_save(_text('sample-iptables-save.txt'))],
        'fw',
        'iptables',
        group_paths=SYSTEM_GROUP_PATHS,
        interface_addresses={'eth0': ['198.51.100.1/24'], 'eth1': []},
    )
    interfaces = {i['name']: i for i in plan.firewall['interfaces']}
    assert interfaces['eth0']['addresses'][0]['inet_addr_mask'] == {
        'address': '198.51.100.1',
        'netmask': '255.255.255.0',
    }
    # Without an address the interface is still found at run time.
    assert interfaces['eth1']['data'] == {'dyn': True}


def test_filter_chains_on_prerouting_only_are_a_mangle_table():
    ruleset = parse_nft_json(
        '{"nftables": [{"table": {"family": "ip", "name": "m"}},'
        '{"chain": {"family": "ip", "table": "m", "name": "post",'
        ' "type": "filter", "hook": "postrouting", "prio": -150, "policy": "accept"}}]}'
    )
    assert ruleset.tables[0].kind == 'mangle'


def _nft_listing(rules, family='inet', prio=0):
    """A listing of one input chain holding *rules* (lists of statements)."""
    import json

    items = [
        {'table': {'family': family, 'name': 't'}},
        {
            'chain': {
                'family': family,
                'table': 't',
                'name': 'input',
                'type': 'filter',
                'hook': 'input',
                'prio': prio,
                'policy': 'drop',
            }
        },
    ]
    for expr in rules:
        items.append(
            {'rule': {'family': family, 'table': 't', 'chain': 'input', 'expr': expr}}
        )
    return json.dumps({'nftables': items})


def test_broadcast_is_not_the_standard_dummy_object():
    """The Standard library's "Dummy" stands for an emptied rule element."""
    _db, _fw, plan = _import(
        [
            parse_iptables_save(
                '*filter\n:INPUT DROP [0:0]\n'
                '-A INPUT -d 255.255.255.255/32 -p udp --dport 67 -j ACCEPT\nCOMMIT\n'
            )
        ],
        'iptables',
    )
    assert 'h-255.255.255.255' in {obj['name'] for obj in plan.objects}


def test_meta_nfproto_restricts_a_rule_without_addresses_to_its_family():
    accept_ssh_v4 = [
        {'match': {'op': '==', 'left': {'meta': {'key': 'nfproto'}}, 'right': 'ipv4'}},
        {
            'match': {
                'op': '==',
                'left': {'payload': {'protocol': 'tcp', 'field': 'dport'}},
                'right': 22,
            }
        },
        {'accept': None},
    ]
    _db, _fw, plan = _import(
        [parse_nft_json(_nft_listing([accept_ssh_v4]))], 'nftables'
    )
    rule_sets = {rs['name']: rs for rs in plan.firewall['rule_sets']}
    assert (rule_sets['Policy']['ipv4'], rule_sets['Policy']['ipv6']) == (True, True)
    (family_only,) = [rs for name, rs in rule_sets.items() if name.startswith('input_')]
    # The action is in a rule set compiled for IPv4 alone.
    assert (family_only['ipv4'], family_only['ipv6']) == (True, False)
    assert family_only['rules'][0]['action'] == 'Accept'


def test_a_negated_destination_of_an_input_rule_goes_behind_the_firewall():
    drop_not_mine = [
        {
            'match': {
                'op': '!=',
                'left': {'payload': {'protocol': 'ip', 'field': 'daddr'}},
                'right': {'set': ['192.0.2.1', '192.0.2.2']},
            }
        },
        {'drop': None},
    ]
    _db, _fw, plan = _import(
        [parse_nft_json(_nft_listing([drop_not_mine], family='ip'))], 'nftables'
    )
    rule_sets = {rs['name']: rs for rs in plan.firewall['rule_sets']}
    outer = rule_sets['Policy']['rules'][0]
    assert outer['action'] == 'Branch'
    assert len(outer['dst']) == 1
    assert outer['dst'][0].endswith('/Firewall:imported')
    (inner,) = next(rs for name, rs in rule_sets.items() if name.startswith('input_'))[
        'rules'
    ]
    assert inner['negations'] == {'dst': True}
    assert inner['action'] == 'Deny'


def test_a_table_at_mangle_priority_is_not_the_filter():
    """Its accept does not end the filtering in the other tables."""
    ruleset = parse_nft_json(_nft_listing([[{'accept': None}]], family='ip', prio=-150))
    assert ruleset.tables[0].kind == 'mangle'


def test_rule_set_names_are_valid_iptables_chain_names():
    """iptables refuses whitespace in a chain name and cuts it at 28."""
    _db, _fw, plan = _import(
        [parse_iptables_save(_text('fwbuilder-ipt.test'))], 'iptables', 'fw'
    )
    for rule_set in plan.firewall['rule_sets']:
        if not rule_set['top']:
            assert ' ' not in rule_set['name'], rule_set['name']
            assert len(rule_set['name']) <= 28, rule_set['name']


def test_a_table_with_filter_and_nat_chains_is_read_as_two():
    """firewalld since 1.0 keeps both in "inet firewalld"."""
    import json

    def chain(name, chain_type, hook):
        return {
            'chain': {
                'family': 'inet',
                'table': 'firewalld',
                'name': name,
                'type': chain_type,
                'hook': hook,
                'prio': 0 if chain_type == 'filter' else -100,
                'policy': 'accept',
            }
        }

    def rule(chain_name, expr):
        return {
            'rule': {
                'family': 'inet',
                'table': 'firewalld',
                'chain': chain_name,
                'expr': expr,
            }
        }

    items = [
        {'table': {'family': 'inet', 'name': 'firewalld'}},
        chain('filter_INPUT', 'filter', 'input'),
        chain('nat_PREROUTING', 'nat', 'prerouting'),
        {'chain': {'family': 'inet', 'table': 'firewalld', 'name': 'nat_PRE_public'}},
        rule('filter_INPUT', [{'reject': None}]),
        rule('nat_PREROUTING', [{'goto': {'target': 'nat_PRE_public'}}]),
    ]
    ruleset = parse_nft_json(json.dumps({'nftables': items}))
    kinds = {t.kind: sorted(t.chains) for t in ruleset.tables}
    assert kinds == {
        'filter': ['filter_INPUT'],
        'nat': ['nat_PREROUTING', 'nat_PRE_public'],
    }


def test_a_blocking_rule_it_cannot_carry_over_blocks_more_instead_of_less():
    """Disabled, a drop rule would let through what the original stopped."""
    _db, _fw, plan = _import(
        [
            parse_iptables_save(
                '*filter\n:INPUT DROP [0:0]\n'
                '-A INPUT -p tcp --dport 3306 -m recent --name db --rcheck -j DROP\n'
                '-A INPUT -p tcp --dport 8080 -m recent --name web --set -j ACCEPT\n'
                'COMMIT\n'
            )
        ],
        'iptables',
    )
    drop, accept = plan.firewall['rule_sets'][0]['rules']
    # The drop is active, without the recent match, and says so.
    assert drop['action'] == 'Deny'
    assert 'disabled' not in drop['options']
    assert drop['options']['color'] == '#C86E6E'
    assert 'blocks more than the original' in drop['comment']
    assert drop['srv']
    # The accept is disabled: without it less passes.
    assert accept['options']['disabled'] is True
    assert (plan.widened_rules, plan.unsupported_rules) == (1, 1)


@pytest.mark.parametrize('platform', ['ipt', 'nft'])
def test_two_branches_into_one_chain_are_no_loop(tmp_path, platform):
    """firewalld reaches a zone's chains on two paths; a diamond is no cycle."""

    items = [
        {'table': {'family': 'ip', 'name': 't'}},
        {
            'chain': {
                'family': 'ip',
                'table': 't',
                'name': 'input',
                'type': 'filter',
                'hook': 'input',
                'prio': 0,
                'policy': 'drop',
            }
        },
    ]
    for name in ('zone', 'a', 'b', 'c'):
        items.append({'chain': {'family': 'ip', 'table': 't', 'name': name}})

    def rule(chain_name, expr):
        return {
            'rule': {'family': 'ip', 'table': 't', 'chain': chain_name, 'expr': expr}
        }

    items += [
        rule('input', [{'jump': {'target': 'zone'}}]),
        rule('zone', [{'jump': {'target': 'a'}}]),
        rule('zone', [{'jump': {'target': 'b'}}]),
        rule('a', [{'jump': {'target': 'c'}}]),
        rule('b', [{'jump': {'target': 'c'}}]),
        rule('c', [{'accept': None}]),
    ]
    db_manager, _fw, _plan = _import(
        [parse_nft_json(json.dumps({'nftables': items}))], 'nftables', 'fw'
    )
    driver, _script = _compile(db_manager, 'fw', tmp_path, platform)
    assert not [w for w in driver.all_warnings if 'creating a loop' in w]


@pytest.mark.parametrize(
    ('source', 'expected'),
    [
        ('-j NFQUEUE --queue-num 0', []),
        ('-j QUEUE', []),
        ('-j NFQUEUE --queue-num 3', ['--queue-num 3']),
    ],
)
def test_iptables_save_reads_a_queue_target(source, expected):
    ruleset = parse_iptables_save(
        f'*filter\n:INPUT DROP [0:0]\n-A INPUT -p tcp --dport 80 {source}\nCOMMIT\n'
    )
    rule = ruleset.tables[0].chains['INPUT'].rules[0]
    assert (rule.action, rule.unsupported) == ('queue', expected)


@pytest.mark.parametrize(
    ('body', 'expected'),
    [
        (None, []),
        ({'num': 0}, []),
        ({'num': 3}, ['queue to 3']),
        ({'flags': ['bypass']}, ["queue flags ['bypass']"]),
    ],
)
def test_nft_json_reads_a_queue_statement(body, expected):
    ruleset = parse_nft_json(_nft_listing([[{'queue': body}]]))
    rule = ruleset.tables[0].chains['input'].rules[0]
    assert (rule.action, rule.unsupported) == ('queue', expected)


@pytest.mark.parametrize(
    ('platform', 'verdict'), [('ipt', '-j QUEUE'), ('nft', 'queue')]
)
def test_a_queued_packet_stays_queued(tmp_path, platform, verdict):
    """Left out, the queue rule let the packet on to the accepts after it."""
    listing = _nft_listing(
        [
            [
                {
                    'match': {
                        'op': '==',
                        'left': {'payload': {'protocol': 'tcp', 'field': 'dport'}},
                        'right': 80,
                    }
                },
                {'queue': None},
            ],
            [{'accept': None}],
        ]
    )
    db_manager, _fw, plan = _import([parse_nft_json(listing)], 'nftables')
    assert plan.unsupported_rules == 0
    _driver, script = _compile(db_manager, 'imported', tmp_path, platform)
    assert verdict in script.read_text()


@pytest.mark.parametrize('platform', ['ipt', 'nft'])
def test_jumps_into_empty_nat_chains_are_left_out(tmp_path, platform):
    """firewalld jumps into a _pre, _log, ... chain of every zone, mostly empty."""
    items = [
        {'table': {'family': 'inet', 'name': 't'}},
        {
            'chain': {
                'family': 'inet',
                'table': 't',
                'name': 'post',
                'type': 'nat',
                'hook': 'postrouting',
                'prio': 100,
                'policy': 'accept',
            }
        },
    ]
    for name in ('zones', 'zone', 'zone_pre', 'zone_post', 'zone_allow'):
        items.append({'chain': {'family': 'inet', 'table': 't', 'name': name}})

    def rule(chain_name, expr):
        return {
            'rule': {'family': 'inet', 'table': 't', 'chain': chain_name, 'expr': expr}
        }

    oif = {'match': {'op': '==', 'left': {'meta': {'key': 'oifname'}}, 'right': 'wan0'}}
    items += [
        rule('post', [{'jump': {'target': 'zones'}}]),
        rule('zones', [oif, {'goto': {'target': 'zone'}}]),
        rule('zone', [{'jump': {'target': 'zone_pre'}}]),
        rule('zone', [{'jump': {'target': 'zone_allow'}}]),
        rule('zone', [{'jump': {'target': 'zone_post'}}]),
        rule('zone_allow', [{'masquerade': None}]),
    ]
    db_manager, fw_id, _plan = _import(
        [parse_nft_json(json.dumps({'nftables': items}))], 'nftables'
    )
    with db_manager.session() as session:
        names = {rs.name for rs in session.get(Firewall, fw_id).rule_sets}
    assert {'zone', 'zone_allow'} <= names
    assert not {'zone_pre', 'zone_post'} & names
    driver, script = _compile(db_manager, 'imported', tmp_path, platform)
    assert driver.all_errors == []
    assert ('MASQUERADE' if platform == 'ipt' else 'masquerade') in script.read_text()


def test_a_second_plan_from_the_same_input_is_the_same():
    """The wizard's input, read once, may be planned for either platform."""
    ruleset = parse_nft_json(
        _nft_listing(
            [
                [
                    {
                        'match': {
                            'op': 'in',
                            'left': {'ct': {'key': 'state'}},
                            'right': ['established', 'related'],
                        }
                    },
                    {'accept': None},
                ],
                [{'accept': None}],
            ]
        )
    )
    plans = [_import([ruleset], platform)[2] for platform in ('nftables', 'iptables')]
    assert [p.firewall['options'].get('accept_established') for p in plans] == [
        True,
        True,
    ]


@pytest.mark.parametrize('platform', ['ipt', 'nft'])
@pytest.mark.parametrize(
    'match',
    [
        '-s 192.168.1.0/24',
        '-m iprange --src-range 192.168.1.1-192.168.1.9',
        '-m iprange ! --src-range 192.168.1.1-192.168.1.9',
        '-m iprange --dst-range 192.168.1.1-192.168.1.9',
    ],
)
def test_a_forward_rule_stays_out_of_the_local_chains(tmp_path, platform, match):
    """Around the firewall's address, the compiler adds an output or input copy.

    That copy would sit ahead of the output rules imported in their own
    right and accept what they drop.
    """
    ruleset = parse_iptables_save(
        '*filter\n:INPUT DROP [0:0]\n:FORWARD DROP [0:0]\n:OUTPUT DROP [0:0]\n'
        f'-A FORWARD {match} -j ACCEPT\n'
        '-A OUTPUT -o lo -j ACCEPT\nCOMMIT\n',
        4,
    )
    addresses = {'eth0': ['192.168.1.1/24'], 'eth1': ['203.0.113.1/24']}
    db_manager, _fw, _plan = _import(
        [ruleset], 'iptables', interface_addresses=addresses
    )
    _driver, script = _compile(db_manager, 'imported', tmp_path, platform)
    text = script.read_text()
    if platform == 'ipt':
        local = [
            line
            for line in text.splitlines()
            if '-A OUTPUT' in line or '-A INPUT' in line
        ]
    else:
        chains = [
            text.split(f'chain {name} {{', 1)[1].split('}', 1)[0]
            for name in ('input', 'output')
        ]
        local = [
            line for chain in chains for line in chain.splitlines() if 'accept' in line
        ]
    assert len(local) == 1, local
    assert 'lo' in local[0]


@pytest.mark.parametrize(
    ('platform', 'masquerade'),
    [('ipt', '! -o lo   -j MASQUERADE'), ('nft', 'oifname != "lo" counter masquerade')],
)
def test_firewalld_zone_nat_compiles_the_way_it_ran(tmp_path, platform, masquerade):
    """Older firewalld goes to every zone; most zone chains are empty.

    A goto into an empty chain is a return, a chain of nothing but such
    gotos is empty itself, and "oifname != lo masquerade" masquerades
    behind whatever interface the packet leaves by.
    """

    def base(name, hook, prio):
        return {
            'chain': {
                'family': 'ip',
                'table': 'firewalld',
                'name': name,
                'type': 'nat',
                'hook': hook,
                'prio': prio,
                'policy': 'accept',
            }
        }

    items = [
        {'table': {'family': 'ip', 'name': 'firewalld'}},
        base('nat_POSTROUTING', 'postrouting', 110),
        base('nat_PREROUTING', 'prerouting', -90),
    ]
    for kind in ('POST', 'PRE'):
        for name in ('ZONES', 'internal', 'internal_allow', 'public', 'public_allow'):
            items.append(
                {
                    'chain': {
                        'family': 'ip',
                        'table': 'firewalld',
                        'name': f'nat_{kind}_{name}',
                    }
                }
            )

    def rule(chain_name, *expr):
        return {
            'rule': {
                'family': 'ip',
                'table': 'firewalld',
                'chain': chain_name,
                'expr': list(expr),
            }
        }

    def oif(name, op='=='):
        return {
            'match': {'op': op, 'left': {'meta': {'key': 'oifname'}}, 'right': name}
        }

    items += [
        rule('nat_POSTROUTING', {'jump': {'target': 'nat_POST_ZONES'}}),
        rule('nat_POST_ZONES', oif('lan0'), {'goto': {'target': 'nat_POST_internal'}}),
        rule('nat_POST_ZONES', {'goto': {'target': 'nat_POST_public'}}),
        rule('nat_POST_internal', {'jump': {'target': 'nat_POST_internal_allow'}}),
        rule('nat_POST_public', {'jump': {'target': 'nat_POST_public_allow'}}),
        rule('nat_POST_public_allow', oif('lo', '!='), {'masquerade': None}),
        # The prerouting side holds no rule at all.
        rule('nat_PREROUTING', {'jump': {'target': 'nat_PRE_ZONES'}}),
        rule('nat_PRE_ZONES', {'goto': {'target': 'nat_PRE_internal'}}),
        rule('nat_PRE_ZONES', {'goto': {'target': 'nat_PRE_public'}}),
        rule('nat_PRE_internal', {'jump': {'target': 'nat_PRE_internal_allow'}}),
        rule('nat_PRE_public', {'jump': {'target': 'nat_PRE_public_allow'}}),
    ]
    db_manager, fw_id, plan = _import(
        [parse_nft_json(json.dumps({'nftables': items}))],
        'nftables',
        interface_addresses={'enp1s0': ['192.0.2.1/24'], 'lan0': ['10.0.0.1/24']},
    )
    assert plan.unsupported_rules == 0
    with db_manager.session() as session:
        names = {rs.name for rs in session.get(Firewall, fw_id).rule_sets}
    assert not {name for name in names if name.startswith('nat_PRE')}, names
    driver, script = _compile(db_manager, 'imported', tmp_path, platform)
    assert (driver.all_errors, driver.all_warnings) == ([], [])
    text = script.read_text()
    assert masquerade in text
    assert 'SNAT' not in text


@pytest.mark.parametrize('platform', ['ipt', 'nft'])
def test_an_ipv4_port_forward_in_an_inet_table_compiles(tmp_path, platform):
    """firewalld puts "meta nfproto ipv4 ... dnat" into a zone chain of inet.

    The IPv6 run of that rule set fills no chain, and the branch into it
    has nothing to jump to - which is no error.
    """
    items = [
        {'table': {'family': 'inet', 'name': 'firewalld'}},
        {
            'chain': {
                'family': 'inet',
                'table': 'firewalld',
                'name': 'nat_PREROUTING',
                'type': 'nat',
                'hook': 'prerouting',
                'prio': -90,
                'policy': 'accept',
            }
        },
        {'chain': {'family': 'inet', 'table': 'firewalld', 'name': 'zone_allow'}},
    ]

    def rule(chain_name, *expr):
        return {
            'rule': {
                'family': 'inet',
                'table': 'firewalld',
                'chain': chain_name,
                'expr': list(expr),
            }
        }

    items += [
        rule('nat_PREROUTING', {'jump': {'target': 'zone_allow'}}),
        rule(
            'zone_allow',
            {
                'match': {
                    'op': '==',
                    'left': {'meta': {'key': 'nfproto'}},
                    'right': 'ipv4',
                }
            },
            {
                'match': {
                    'op': '==',
                    'left': {'payload': {'protocol': 'tcp', 'field': 'dport'}},
                    'right': 8081,
                }
            },
            {'dnat': {'family': 'ip', 'addr': '10.10.0.10', 'port': 80}},
        ),
    ]
    db_manager, _fw, plan = _import(
        [parse_nft_json(json.dumps({'nftables': items}))],
        'nftables',
        interface_addresses={'eth0': ['192.0.2.1/24']},
    )
    assert plan.unsupported_rules == 0
    driver, script = _compile(db_manager, 'imported', tmp_path, platform)
    assert driver.all_errors == []
    assert '10.10.0.10' in script.read_text()


# -- routes --


def _routes():
    return [
        parse_ip_route_json(_text('sample-routes4.json'), 4),
        parse_ip_route_json(_text('sample-routes6.json'), 6),
    ]


def test_ip_route_reads_what_an_administrator_configured():
    """iproute2 leaves out type unicast, proto boot, table main, scope global."""
    v4, v6 = _routes()
    by_dst = {r.dst.text if r.dst else 'default': r for r in v4.routes}
    assert sorted(by_dst) == [
        '10.1.0.0/16',
        '10.2.0.0/16',
        '10.3.0.5',
        '10.4.0.0/16',
        '10.5.0.0/16',
        'default',
    ]
    assert by_dst['default'].metric == 100
    assert [h.gateway.text for h in by_dst['10.4.0.0/16'].next_hops] == [
        '192.0.2.20',
        '198.51.100.20',
    ]
    assert by_dst['10.3.0.5'].unsupported == ['mtu 1400', 'source address 192.0.2.1']
    assert by_dst['10.5.0.0/16'].unsupported == ['flag onlink']
    left_out = ' '.join(text for _severity, text in v4.messages)
    for what in ('proto dhcp', 'table 100', 'type blackhole'):
        assert what in left_out
    # The kernel's own and the IPv6 router preference are no loss, and the
    # metric the kernel gives an IPv6 route that names none is no metric.
    assert [
        (r.dst.text if r.dst else 'default', r.metric, r.unsupported) for r in v6.routes
    ] == [
        ('2001:db8:5::/48', 0, []),
        ('default', 0, []),
    ]


def test_ip_route_without_a_family_lists_both_and_counts_each_once():
    mixed = (
        '[{"dst":"10.1.0.0/16","gateway":"192.0.2.254","dev":"eth0","flags":[]},'
        '{"dst":"2001:db8:5::/48","gateway":"2001:db8::5","dev":"eth0",'
        '"metric":1024,"flags":[],"pref":"medium"}]'
    )
    assert [r.family for r in parse_ip_route_json(mixed).routes] == [4, 6]
    assert [r.family for r in parse_ip_route_json(mixed, 4).routes] == [4]


@pytest.mark.parametrize('platform', ['ipt', 'nft'])
def test_imported_routes_compile_into_the_route_commands(tmp_path, platform):
    db_manager, _fw, plan = _import(
        [],
        'nftables',
        routes=_routes(),
        interface_addresses=parse_ip_addr_json(_text('sample-routes-addr.json')),
    )
    assert (plan.imported_routes, plan.marked_routes, plan.unsupported_rules) == (
        8,
        1,
        1,
    )
    driver, script = _compile(db_manager, 'imported', tmp_path, platform)
    assert (driver.all_errors, driver.all_warnings) == ([], [])
    commands = [
        ' '.join(line.split())
        for line in script.read_text().splitlines()
        if line.strip().startswith(('$IP route add', '$IP -6 route add', 'nexthop'))
    ]
    assert commands == [
        '$IP route add default metric 100 via 192.0.2.254 dev eth0 \\',
        '$IP route add 10.1.0.0/16 via 198.51.100.254 dev eth1 \\',
        '$IP route add 10.2.0.0/16 dev eth1 \\',
        '$IP route add 10.3.0.5 via 192.0.2.10 dev eth0 \\',
        '$IP -6 route add 2001:db8:5::/48 via 2001:db8::5 dev eth0 \\',
        '$IP -6 route add default via fe80::1 dev eth0 \\',
        '$IP route add 10.4.0.0/16 \\',
        'nexthop via 192.0.2.20 dev eth0 \\',
        'nexthop via 198.51.100.20 dev eth1 \\',
    ]


def test_a_route_through_a_gateway_off_the_link_is_imported_disabled():
    """The compiler refuses an unreachable gateway, and the activation stops."""
    db_manager, fw_id, _plan = _import([], 'nftables', routes=_routes())
    rules = _rules(db_manager, fw_id, 'Routing')
    marked = [(options, comment) for options, comment, _rows in rules if comment]
    onlink = [o for o, c in marked if 'onlink' in c]
    assert onlink and onlink[0].get('disabled') is True
    mtu = [o for o, c in marked if 'mtu 1400' in c]
    assert mtu and not mtu[0].get('disabled') and mtu[0].get('color')


def test_an_imported_firewall_has_the_rule_sets_a_new_one_has():
    _db, _fw, plan = _import([], 'nftables')
    assert sorted(rs['type'] for rs in plan.firewall['rule_sets'] if rs['top']) == [
        'NAT',
        'Policy',
        'Routing',
    ]
