"""
SQLAlchemy 2.0 ORM models for libfwbuilder data structures.

Association tables replace the old FWReference / RuleElement class trees.
"""

# Import all submodules so every ORM class registers on the shared Base.metadata.
from ._addresses import (
    Address,
    AddressRange,
    IPv4,
    IPv6,
    MultiAddressRunTime,
    Network,
    NetworkIPv6,
    PhysAddress,
)
from ._base import (
    Base,
    enable_sqlite_fks,
)
from ._database import (
    FWObjectDatabase,
    Library,
)
from ._devices import (
    Cluster,
    Firewall,
    Host,
    Interface,
)
from ._groups import (
    AddressTable,
    AttachedNetworks,
    ClusterGroup,
    DNSName,
    DynamicGroup,
    FailoverClusterGroup,
    Group,
    IntervalGroup,
    MultiAddress,
    ObjectGroup,
    ServiceGroup,
    StateSyncClusterGroup,
    group_membership,
)
from ._rules import (
    NAT,
    NATRule,
    Policy,
    PolicyRule,
    Routing,
    RoutingRule,
    Rule,
    RuleSet,
    rule_elements,
)
from ._services import (
    CustomService,
    ICMP6Service,
    ICMPService,
    IPService,
    Interval,
    Service,
    TCPService,
    TCPUDPService,
    TagService,
    UDPService,
    UserService,
)
from ._types import (
    Direction,
    Inet6AddrMask,
    InetAddr,
    InetAddrMask,
    JSONEncodedSet,
    NATAction,
    NATRuleType,
    PolicyAction,
    RoutingRuleType,
    StandardId,
    TCPFlag,
)

__all__ = [
    'Address',
    'AddressRange',
    'AddressTable',
    'AttachedNetworks',
    'Base',
    'Cluster',
    'ClusterGroup',
    'CustomService',
    'DNSName',
    'Direction',
    'DynamicGroup',
    'FWObjectDatabase',
    'FailoverClusterGroup',
    'Firewall',
    'Group',
    'Host',
    'ICMP6Service',
    'ICMPService',
    'IPService',
    'IPv4',
    'IPv6',
    'Inet6AddrMask',
    'InetAddr',
    'InetAddrMask',
    'Interface',
    'Interval',
    'IntervalGroup',
    'JSONEncodedSet',
    'Library',
    'MultiAddress',
    'MultiAddressRunTime',
    'NAT',
    'NATAction',
    'NATRule',
    'NATRuleType',
    'Network',
    'NetworkIPv6',
    'ObjectGroup',
    'Policy',
    'PolicyAction',
    'PolicyRule',
    'Routing',
    'RoutingRule',
    'RoutingRuleType',
    'Rule',
    'RuleSet',
    'Service',
    'ServiceGroup',
    'StandardId',
    'StateSyncClusterGroup',
    'TCPFlag',
    'TCPService',
    'TCPUDPService',
    'TagService',
    'UDPService',
    'UserService',
    'enable_sqlite_fks',
    'group_membership',
    'PhysAddress',
    'rule_elements',
]
